server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: " "
    url: jdbc:postgresql://localhost:5432/registration
    username: ""

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true
  mail:
    default-encoding: Big5
    host: smtp.gmail.com
    password: " "
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            timeout: 10000
    protocol: smtp
    username: " "

